### ISSUE TITLE
[BUG] Requirement package pyyaml won't be installed.

### ISSUE THREAD

**Issue by ForeverOpp** [danhper/python-i18n#19]
I installed it via `pip install python-i18n`, and it shows installed successfully. But I can't use yaml file and I soon found that the requirement package `pyyaml` wasn't installed automatically. I tested it on macOS 10.15.6 and Windows 10 2004. They both showed that problem.

**Comment by danhper** [comment]
Hi!
Yaml is optional so this is the desired behavior. It is documented in the README: https://github.com/danhper/python-i18n#installation

**Comment by ForeverOpp** [comment]
Sorry. I checked `README` even the source code many times but I still not found a tips to install it until I checked the `requirements.txt`. SoI think users should be explicitly reminded to install pyyaml.

**Comment by danhper** [comment]
The users do not need to install pyyaml themselves.
The README explicitly says:

> If you want to use YAML to store your translations, use
> pip install python-i18n[YAML]

which installs `pyyaml` too.
