### ISSUE TITLE
installation issue by poetry

### ISSUE THREAD

**Issue by CarolHsu** [danhper/python-i18n#20]
Might not an issue for thin repo but would like to ask here as well.

I have try to install by `poetry add python-i18n[YAML]` and see it did have `extras` information with `yaml`
However, when I realize this doesn't really include `i18n.loaders.yaml_loader`.

Please suggest if in any case someone knows a better solution for poetry! Apprecaite!

**Comment by danhper** [comment]
If it is installed using the `YAML` extra it should include `pyyaml` as a dependency.
What issue are you facing?

**Comment by CarolHsu** [comment]
yes it works, sorry for late reply, many appreciation!
