### ISSUE TITLE
Translation cannot start with %

### ISSUE THREAD

**Issue by stefansimik** [danhper/python-i18n#21]
Hi, if translation starts with '%' character,
translation fails on error:

Example - if translation is:

`perc_of_clients: % of clients`

then error is thrown:

`I18nFileLoadError: Invalid YAML: while scanning for the next token found character '%', that cannot start any token`

What can I do, to allow % character in translations?

**Comment by danhper** [comment]
Hi,
You can simply quote the string, it should work:

```
perc_of_clients: "% of clients"
```

Please comment if that does not fix it.

**Comment by stefansimik** [comment]
> Hi,
> You can simply quote the string, it should work:
> 
> ```
> perc_of_clients: "% of clients"
> ```
> 
> Please comment if that does not fix it.

Hi, this does not really work. That means, this still throws an error:
`free_sentence: "25% of people are young people."`

What helped is this syntax - write character % twice: 
`free_sentence: 25%% of people are young people.`
