### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by jayvdb** [danhper/python-i18n#25]
The latest tag at the moment is 0.3.0, while PyPI has 0.3.9.

**Comment by danhper** [comment]
I just pushed the latest tag.

**Comment by jayvdb** [comment]
Perfect, thanks.  All packaged with tests running on openSUSE.
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-python-i18n
I'll submit it to the main package collection after the next release.
