### ISSUE TITLE
Subfolders don't work

### ISSUE THREAD

**Issue by Pukimaa** [danhper/python-i18n#34]
My folder structure is as following:
```
| i18n
   | info
      | en.yml
      | de.yml
      | hr.yml
   | config
      | en.yml
      | de.yml
      | hr.yml
```

And if I load the files as following:
`i18n.load_path.append(f"{os.getcwd()}{path_trimmer}i18n")` (path trimmer is `/` or `\\` depending on the os) or just `i18n.load_path.append("i18n")`

And I get translation `config.key` or `info.key` I don't get the translation but only the input. However in the README it was stated:

> If your files are in subfolders, the foldernames are also used as namespaces, so for example if your translation root path is /path/to/translations and you have the file /path/to/translations/my/app/name/foo.en.yml, the translation namespace for the file will be my.app.name and the file keys will therefore be accessible from my.app.name.foo.my_key.

**Comment by Pukimaa** [comment]
Pingin as it has high priority: @danhper

**Comment by Pukimaa** [comment]
Also tried just to append "i18n" as the folder. That also didn't work. I mean everything works if I put it in the i18n folder.

**Comment by pos1er** [comment]
faced with the same problem, have you found a solution?

> Also tried just to append "i18n" as the folder. That also didn't work. I mean everything works if I put it in the i18n folder.

**Comment by Pukimaa** [comment]
I've created another version ([tako-discord/python-i18n](https://github.com/tako-discord/python-i18n) with the help from someone else. But you need to set the format to `locale.extension` (or however it was...so it removes the namespace) and then it works. However I haven't tried if it now also works without a subdir.
`i18n/category/en.yml` -> `category.key`

**Comment by RathanakSreang** [comment]
@pos1er  @Pukimaa  make sure you have `pyyaml` install on your os.

**Comment by Pukimaa** [comment]
> @pos1er  @Pukimaa  make sure you have `pyyaml` install on your os.

Not the issue. Having the folder structure different is no problem too.
